Feature/attack/drupal scan
tklab-tud/ID2T pull request #118
Opened 2023-04-08 17:40 UTC by Abdiiir

- function to generate unique random IPv4 address within the specified IP network
- function to generate and track  ephemeral port for convos.
- added drupal CMS scan attack

2023-04-08 23:49 UTC, pepper-jk commented on .gitignore
Please remove this change from the pull request.

Our intention here was to avoid accidental committing of input or output pcaps.

On the master branch this should stay that way.

2023-04-08 23:53 UTC, pepper-jk requested changes

2023-04-08 23:53 UTC, pepper-jk commented on code/Attack/DrupalScan.py
> +
Please avoid trailing white spaces.

2023-04-08 23:53 UTC, pepper-jk commented on code/Attack/DrupalScan.py
> +                timestamp_next_pkt = self.timestamp_controller.next_timestamp() #+# inter_arrival_times[self.pkt_num]
Please remove out commented code.

If this is the final version of the attack, it should not be necessary to include this.

2023-04-09 00:08 UTC, pepper-jk commented
The commits  e97e3eb, a91196a can be squashed into one commit.

e97e3eb and 4662015 should have more descriptive commit messages.

Please try the following format:

e97e3eb
```
Durpal Scan: <Add the attack>

<description of attack>
<short explanation on how the attack functions>
```

4662015
```
Durpal Scan: <use common CMS functionalities>

<which functions are used>
<explain why they are used>
<how does it improve the attack>
```

Same scheme might be applied to 1282381:

```
Base Attack: <add common CMS functionalities>

<describe functionalities with reference to function name>
<explain how to use them XOR (at least) give an example>
```

2023-04-09 00:11 UTC, pepper-jk commented
I like the initiative here. Looks like a reasonably well implemented attack.

Only had time to glance over it though. Hopefully, I will find time to test it myself and review the actual  attack implementation soon. In the meantime please go over my requested changes and let me know if you have any questions.

2023-04-09 12:01 UTC, Abdiiir commented
Hi @pepper-jk , 

Thanks for the review. I appreciate you taking the time. 

I will implement the requested changes and force-push.

Happy holidays to you too :))

2023-04-23 15:15 UTC, closed without merging